[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
# Install ALL dependencies (including devDeps) so nest build can work
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx nest build"
]

[start]
cmd = "node dist/main"
